### ISSUE TITLE
Error in 'scanForHeterozygotes' function

### ISSUE THREAD

**Issue by jk86754** [pappewaio/AllelicImbalance#3]
Hi,

 

I generated BAM files using the STAR aligner. I am having some issues working with these BAM files in AllelicImbalance:

 

I would appreciate some help with the issue.

 Jozsef 

> pathToFiles='h:/AGP_hg19_filtered_fastq_bam'
> searchArea<-GRanges(seqnames = c("chr11"),ranges = IRanges(35228000, 35230000))
> reads <- impBamGAL(pathToFiles,searchArea,verbose=T)
Reading bam file 1 with filename AGP001_Aligned.sortedByCoord.out.bam 
stored AGP001_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 2 with filename AGP002_Aligned.sortedByCoord.out.bam 
stored AGP002_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 3 with filename AGP003_Aligned.sortedByCoord.out.bam 
stored AGP003_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 4 with filename AGP004_Aligned.sortedByCoord.out.bam 
stored AGP004_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 5 with filename AGP006_Aligned.sortedByCoord.out.bam 
stored AGP006_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 6 with filename AGP007_Aligned.sortedByCoord.out.bam 
stored AGP007_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 7 with filename AGP009_Aligned.sortedByCoord.out.bam 
stored AGP009_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 8 with filename AGP012_Aligned.sortedByCoord.out.bam 
stored AGP012_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 9 with filename AGP013_Aligned.sortedByCoord.out.bam 
stored AGP013_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 10 with filename AGP022_Aligned.sortedByCoord.out.bam 
stored AGP022_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 11 with filename AGP025_Aligned.sortedByCoord.out.bam 
stored AGP025_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 12 with filename AGP027_Aligned.sortedByCoord.out.bam 
stored AGP027_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 13 with filename AGP029_Aligned.sortedByCoord.out.bam 
stored AGP029_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 14 with filename AGP040_Aligned.sortedByCoord.out.bam 
stored AGP040_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 15 with filename AGP041_Aligned.sortedByCoord.out.bam 
stored AGP041_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 16 with filename AGP044_Aligned.sortedByCoord.out.bam 
stored AGP044_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 17 with filename AGP046_Aligned.sortedByCoord.out.bam 
stored AGP046_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 18 with filename AGP061_Aligned.sortedByCoord.out.bam 
stored AGP061_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 19 with filename H1_Aligned.sortedByCoord.out.bam 
stored H1_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 20 with filename H10_Aligned.sortedByCoord.out.bam 
stored H10_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 21 with filename H11_Aligned.sortedByCoord.out.bam 
stored H11_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 22 with filename H12_Aligned.sortedByCoord.out.bam 
stored H12_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 23 with filename H13_Aligned.sortedByCoord.out.bam 
stored H13_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 24 with filename H14_Aligned.sortedByCoord.out.bam 
stored H14_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 25 with filename H15_Aligned.sortedByCoord.out.bam 
stored H15_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 26 with filename H2_Aligned.sortedByCoord.out.bam 
stored H2_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 27 with filename H3_Aligned.sortedByCoord.out.bam 
stored H3_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 28 with filename H4_Aligned.sortedByCoord.out.bam 
stored H4_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 29 with filename H5_Aligned.sortedByCoord.out.bam 
stored H5_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 30 with filename H6_Aligned.sortedByCoord.out.bam 
stored H6_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 31 with filename H7_Aligned.sortedByCoord.out.bam 
stored H7_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 32 with filename H8_Aligned.sortedByCoord.out.bam 
stored H8_Aligned.sortedByCoord.out.bam in BamGAL 
Reading bam file 33 with filename H9_Aligned.sortedByCoord.out.bam 
stored H9_Aligned.sortedByCoord.out.bam in BamGAL 

> heterozygotePositions <- scanForHeterozygotes(reads, maxReads=1e+07, verbose=TRUE)
Investigating chromosome chr11 
Investigating sample 1 out of 33 
Error in new[start[i]:(start[i] + length(toKeep[[i]]) - 1), i] <- charList[[i]][toKeep[[i]]] : 
  number of items to replace is not a multiple of replacement length

> sessionInfo()

R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
 [1] stats4    parallel  grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] org.Hs.eg.db_3.0.0      RSQLite_1.0.0           DBI_0.3.1               AnnotationDbi_1.28.1    Biobase_2.26.0         
 [6] AllelicImbalance_1.4.0  GenomicAlignments_1.2.2 Rsamtools_1.18.3        Biostrings_2.34.1       XVector_0.6.0          
[11] GenomicRanges_1.18.4    GenomeInfoDb_1.2.4      IRanges_2.0.1           S4Vectors_0.4.0         BiocGenerics_0.12.1    

loaded via a namespace (and not attached):
 [1] acepack_1.3-3.3          base64enc_0.1-2          BatchJobs_1.5            BBmisc_1.8              
 [5] BiocParallel_1.0.3       biomaRt_2.22.0           biovizBase_1.14.1        bitops_1.0-6            
 [9] brew_1.0-6               BSgenome_1.34.1          checkmate_1.5.0          cluster_1.15.3          
[13] codetools_0.2-9          colorspace_1.2-4         dichromat_2.0-0          digest_0.6.4            
[17] fail_1.2                 foreach_1.4.2            foreign_0.8-61           Formula_1.1-2           
[21] GenomicFeatures_1.18.3   Gviz_1.10.10             Hmisc_3.14-6             iterators_1.0.7         
[25] lattice_0.20-29          latticeExtra_0.6-26      matrixStats_0.10.3       munsell_0.4.2           
[29] nnet_7.3-8               plyr_1.8.1               R.methodsS3_1.6.1        RColorBrewer_1.0-5      
[33] Rcpp_0.11.3              RCurl_1.95-4.4           rpart_4.1-8              rtracklayer_1.26.2      
[37] scales_0.2.4             sendmailR_1.2-1          splines_3.1.2            stringr_0.6.2           
[41] survival_2.37-7          tools_3.1.2              VariantAnnotation_1.12.9 XML_3.98-1.1            
[45] zlibbioc_1.12.0

**Comment by pappewaio** [comment]
Hi!
This looks very similar to issue #2 . The bug is fixed in the devel version of R. Will write once more when the change has taken place in the release version of R as well.

**Comment by pappewaio** [comment]
The changes are now in the release branch. If you don't want to wait until the next build cycle (which would be within 24h), then you can use svn to checkout the package and install it from the terminal by these commands:
```
svn co https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_0/madman/Rpacks/AllelicImbalance --username readonly --password readonly

R CMD INSTALL AllelicImbalance
```

**Comment by jk86754** [comment]
Sorry, I don't mean to be a nuisance. Still getting the same issue with
AllelicImbalance_1.4.1:

> heterozygotePositions <- scanForHeterozygotes(reads, maxReads=1e+07,
verbose=TRUE)
Investigating chromosome chr11
Investigating sample 1 out of 33
Error in new[start[i]:(start[i] + length(toKeep[[i]]) - 1), i] <-
charList[[i]][toKeep[[i]]] :
  number of items to replace is not a multiple of replacement length
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8
 [2] LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8
 [4] LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8
 [6] LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8
 [8] LC_NAME=C
 [9] LC_ADDRESS=C
[10] LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8
[12] LC_IDENTIFICATION=C

attached base packages:
 [1] stats4    parallel  grid      stats
 [5] graphics  grDevices utils     datasets
 [9] methods   base

other attached packages:
 [1] org.Hs.eg.db_3.0.0
 [2] RSQLite_1.0.0
 [3] DBI_0.3.1
 [4] AnnotationDbi_1.28.1
 [5] Biobase_2.26.0
 [6] AllelicImbalance_1.4.1
 [7] GenomicAlignments_1.2.2
 [8] Rsamtools_1.18.3
 [9] Biostrings_2.34.1
[10] XVector_0.6.0
[11] GenomicRanges_1.18.4
[12] GenomeInfoDb_1.2.4
[13] IRanges_2.0.1
[14] S4Vectors_0.4.0
[15] BiocGenerics_0.12.1

loaded via a namespace (and not attached):
 [1] acepack_1.3-3.3
 [2] base64enc_0.1-2
 [3] BatchJobs_1.5
 [4] BBmisc_1.9
 [5] BiocParallel_1.0.3
 [6] biomaRt_2.22.0
 [7] biovizBase_1.14.1
 [8] bitops_1.0-6
 [9] brew_1.0-6
[10] BSgenome_1.34.1
[11] checkmate_1.5.1
[12] cluster_2.0.1
[13] codetools_0.2-11
[14] colorspace_1.2-6
[15] dichromat_2.0-0
[16] digest_0.6.8
[17] fail_1.2
[18] foreach_1.4.2
[19] foreign_0.8-63
[20] Formula_1.2-0
[21] GenomicFeatures_1.18.3
[22] ggplot2_1.0.0
[23] gtable_0.1.2
[24] Gviz_1.10.10
[25] Hmisc_3.15-0
[26] iterators_1.0.7
[27] lattice_0.20-30
[28] latticeExtra_0.6-26
[29] MASS_7.3-39
[30] matrixStats_0.14.0
[31] munsell_0.4.2
[32] nnet_7.3-9
[33] plyr_1.8.1
[34] proto_0.3-10
[35] RColorBrewer_1.1-2
[36] Rcpp_0.11.5
[37] RCurl_1.95-4.5
[38] reshape2_1.4.1
[39] rpart_4.1-9
[40] rtracklayer_1.26.2
[41] scales_0.2.4
[42] sendmailR_1.2-1
[43] splines_3.1.3
[44] stringr_0.6.2
[45] survival_2.38-1
[46] tools_3.1.3
[47] VariantAnnotation_1.12.9
[48] XML_3.98-1.1
[49] zlibbioc_1.12.0

On Wed, Mar 11, 2015 at 6:27 AM, Jesper R. Gådin <notifications@github.com>
wrote:

> Closed #3 <https://github.com/pappewaio/AllelicImbalance/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pappewaio/AllelicImbalance/issues/3#event-249985814>.
>



-- 
"Early to bed and early to rise makes a man healthy, wealthy, and wise."

-Benjamin Franklin

**Comment by lassefolkersen** [comment]
No nuisance at all, we are happy to receive feedback. In fact your comment
lead me to think this might be star-aligner specific. I also only saw it in
data from star. What do you think Jesper?

**Comment by pappewaio** [comment]
It is hard to tell without some example data if this is a STAR or alignment specific thing, but I see now that the error message actually differs from #2 , so there is something else going on. Think I can manage to have a fix until next Monday using another cigar-translator, which has been on the todo-list to implement anyway, because it uses a faster algorithm.

**Comment by pappewaio** [comment]
Now the devel version has a new, first of all faster scanForHeterozygotes, and while the most code has been replaced, the error is hopefully gone. 

I will make the change in the release branch  tomorrow.

**Comment by pappewaio** [comment]
The new changes are now in the release branch. If you don't want to wait until the next build cycle (which would be within 24h), then you can as before use svn to checkout the package and install it from the terminal by these commands:
```
svn co https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_0/madman/Rpacks/AllelicImbalance --username readonly --password readonly

R CMD INSTALL AllelicImbalance
```
